config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

scope module: :user do
  root to: 'homes#top'
  get '/items', to: 'homes#menu', as: 'menu'
  get '/openinghour', to: 'homes#opening', as: 'opening'
  get '/access', to: 'homes#access', as: 'access'
  get '/contact', to: 'homes#contact', as: 'contact'
end

namespace :admin do
  root to: 'homes#top'
  resources :items, except: [:show]
  resources :notices, except: [:show]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items
  
end

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :genre
  
end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def index
  end 
  
  def new
  end 
  
  def create
  end 
  
  def edit
  end 
  
  def update
  end 
  
  def destroy 
  end 
  
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

  def top
  end

  def menu
  end

  def opening
  end

  def access
  end

  def contact
  end

end

app/helpers/admin/homems_helper.rb
module Admin::HomemsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/notices_helper.rb
module Admin::NoticesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mantra</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://kit.fontawesome.com/8cc696f355.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #EEB006;">
    <nav class="container-fluid navbar navbar-expand-lg navbar-light" style="background-color: #EEB006; margin: 0;">
      <div class="col-4"></div>
      <div class="col-4 d-flex justify-content-center">
        <% if admin_signed_in? %>
          <%= link_to admin_root_path, class: 'navbar-brand' do %>
            <%= image_tag("onion.png", alt: "MANTRA") %>
          <% end %>
        <% else %>
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag("onion.png", alt: "MANTRA") %>
          <% end %>
        <% end %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="col-4 d-flex justify-content-center">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mx-auto">
            <% if admin_signed_in? %>
              <li>
                ※管理者ログイン中
              </li>
              <li class="nav-item">
                <%= link_to admin_items_path, class: "nav-link text-right" do %>
                  <button>
                    メニュー管理
                  </button>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to admin_notices_path, class: "nav-link text-right" do %>
                  <button>
                    お知らせ管理
                  </button>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-right" do %>
                  <button>
                    ログアウト
                  </button>
                <% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to menu_path, class: "nav-link text-right" do %>
                  <button class="header-button">MENU</button>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to opening_path, class: "nav-link text-right" do %>
                  <button class="header-button">OPENING HOUR</button>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to access_path, class: "nav-link text-right" do %>
                  <button class="header-button">ACCESS</button>
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to contact_path, class: "nav-link text-right" do %>
                  <button class="header-button">CONTACT</button>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>